# Generated by kriolu-kloud-idp
# App: demo-api | Environment: homolog | Team: backend

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket         = "kriolu-kloud-terraform-tfstates"
    key            = "apps-terraform/homolog/demo-api-us-east-1.tfstate"
    region         = "us-east-1"
    dynamodb_table = "kriolu-kloud-apps-terraform-lock"
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Environment = var.environment_name
      Service     = var.tag_service
      Owner       = var.tag_owner
      CostCenter  = var.tag_costcenter
    }
  }
}

module "homolog_demo_api" {
  source = "../../idp-app"

  aws_region          = var.aws_region
  environment_name    = var.environment_name
  cluster_environment = var.cluster_environment
  app_name            = var.app_name
  port                = var.port
  domain              = var.domain
}
